#!/usr/bin/env python3
"""Build script for drift website.

Generates HTML pages from markdown and other data sources.
"""

import json
import os
import subprocess
from pathlib import Path
from datetime import datetime

# Paths
DOCS_DIR = Path("docs")
POSTS_DIR = Path("docs/_posts")
TOOLS_MD = Path("../TOOLS.md")
KNOWLEDGE_BASE_JSON = Path("docs/knowledge_base.json")

# Configuration
POSTS = [p for p in POSTS_DIR.glob("*.md") if not p.name.startswith("_")]
if not POSTS:
    raise RuntimeError(f"No markdown posts found in {POSTS_DIR}")

# Load tool inventory
def load_tools():
    """Parse TOOLS.md and return list of tools."""
    tools = []
    with open(TOOLS_MD) as f:
        lines = f.readlines()
    
    # Skip header
    in_tools = False
    for line in lines:
        line = line.strip()
        if line.startswith("## Tools"):
            in_tools = True
            continue
        if in_tools and line.startswith("## "):
            break
        if in_tools and line and not line.startswith("#"):
            tools.append(line)
    return tools

# Generate posts
def generate_posts():
    """Convert markdown posts to HTML."""
    for md_file in sorted(POSTS):
        html_file = DOCS_DIR / f"{md_file.stem}.html"
        
        # Read markdown
        with open(md_file) as f:
            body = f.read()
        
        # Convert markdown to HTML
        from markdown import markdown
        html_body = markdown(body, extensions=["fenced_code", "tables"])
        
        # Generate HTML page
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{md_file.stem}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <nav>
            <a href="index.html">Home</a>
            <a href="runs.html">Runs</a>
            <a href="knowledge_base.html">Knowledge Base</a>
            <a href="tools.html">Tools</a>
        </nav>
    </header>
    <main>
        {html_body}
    </main>
    <footer>
        <p>Generated by drift build script</p>
    </footer>
</body>
</html>"""
        
        with open(html_file, "w") as f:
            f.write(html)
        print(f"Generated {html_file}")

# Generate knowledge base page
def generate_knowledge_base():
    """Generate knowledge base visualization page."""
    if not KNOWLEDGE_BASE_JSON.exists():
        print(f"Warning: {KNOWLEDGE_BASE_JSON} not found")
        return
    
    with open(KNOWLEDGE_BASE_JSON) as f:
        data = json.load(f)
    
    # Generate HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Knowledge Base - Drift</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <nav>
            <a href="index.html">Home</a>
            <a href="runs.html">Runs</a>
            <a href="knowledge_base.html">Knowledge Base</a>
            <a href="tools.html">Tools</a>
        </nav>
    </header>
    <main>
        <h1>Knowledge Base</h1>
        <p>Summary: {len(data)} entries</p>
        <div id="entries"></div>
    </main>
    <footer>
        <p>Generated by drift build script</p>
    </footer>
</body>
</html>"""
    
    with open(DOCS_DIR / "knowledge_base.html", "w") as f:
        f.write(html)
    print("Generated knowledge_base.html")

# Generate tools page
def generate_tools():
    """Generate tools documentation page."""
    tools = load_tools()
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tools - Drift</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <nav>
            <a href="index.html">Home</a>
            <a href="runs.html">Runs</a>
            <a href="knowledge_base.html">Knowledge Base</a>
            <a href="tools.html">Tools</a>
        </nav>
    </header>
    <main>
        <h1>Tool Inventory</h1>
        <p>Summary: {len(tools)} tools documented</p>
        <div id="entries"></div>
    </main>
    <footer>
        <p>Generated by drift build script</p>
    </footer>
</body>
</html>"""
    
    with open(DOCS_DIR / "tools.html", "w") as f:
        f.write(html)
    print("Generated tools.html")

# Generate runs page
def generate_runs_json():
    """Generate runs.json from RUNS.md."""
    runs_file = Path("RUNS.md")
    if not runs_file.exists():
        print(f"Warning: {runs_file} not found")
        return []
    
    runs = []
    in_table = False
    
    with open(runs_file) as f:
        for line in f:
            line = line.strip()
            if line.startswith("|"):
                if not in_table:
                    # Check if this is a table header
                    parts = line.split("|")
                    if len(parts) >= 3 and parts[1].strip().isdigit():
                        in_table = True
                        continue
                else:
                    parts = line.split("|")
                    if len(parts) >= 3:
                        run_num = parts[1].strip()
                        date_str = parts[2].strip()
                        if run_num.isdigit() and date_str:
                            runs.append({
                                "run": int(run_num),
                                "date": date_str,
                                "ended": parts[3].strip() if len(parts) > 3 else "unknown",
                                "turns": int(parts[4].strip()) if len(parts) > 4 and parts[4].strip().isdigit() else 0,
                                "tokens": int(parts[5].strip()) if len(parts) > 5 and parts[5].strip().isdigit() else 0
                            })
    
    # Save to file
    with open(DOCS_DIR / "runs.json", "w") as f:
        json.dump(runs, f, indent=2)
    
    print(f"Generated runs.json with {len(runs)} runs")
    return runs

# Generate runs.html visualization
def generate_runs_page(runs):
    """Generate runs.html visualization page."""
    # Group by end type
    groups = {"stop": [], "out_of_turns": [], "error": [], "interrupt": []}
    for run in runs:
        end_type = run.get("ended", "unknown")
        if end_type in groups:
            groups[end_type].append(run)
        else:
            groups["other"].append(run)
    
    # Create SVG visualization
    svg_width = 800
    svg_height = 400
    padding = 40
    chart_width = svg_width - padding * 2
    chart_height = svg_height - padding * 2
    
    # Draw timeline
    timeline_lines = []
    current_y = padding + 20
    
    # Draw axis
    timeline_lines.append(f'<line x1="{padding}" y1="{svg_height - padding}" x2="{svg_width - padding}" y2="{svg_height - padding}" stroke="#666" stroke-width="2" />')
    
    # Draw end type markers
    colors = {"stop": "#22c55e", "out_of_turns": "#f59e0b", "error": "#ef4444", "interrupt": "#3b82f6", "other": "#6b7280"}
    y_positions = {}
    current_y = padding + 50
    for end_type, color in colors.items():
        if groups[end_type]:
            y_positions[end_type] = current_y
            timeline_lines.append(f'<rect x="{padding}" y="{current_y - 10}" width="{chart_width}" height="20" fill="{color}" opacity="0.3" />')
            timeline_lines.append(f'<text x="{padding}" y="{current_y + 5}" fill="{color}" font-size="12">{end_type}</text>')
            current_y += 30
    
    # Draw runs as marks on timeline
    marks = []
    for run in runs:
        if run["date"] in y_positions:
            x = padding + (run["run"] / 491) * chart_width
            y = y_positions[run["date"]] + 5
            end_type = run.get("ended", "other")
            color = colors.get(end_type, colors["other"])
            marks.append(f'<circle cx="{x}" cy="{y}" r="6" fill="{color}" stroke="white" stroke-width="2" data-run="{run["run"]}" data-date="{run["date"]}" data-ended="{end_type}" />')
    
    # Build HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Runs - Drift</title>
    <link rel="stylesheet" href="style.css">
    <style>
        .tooltip {{
            position: absolute;
            background: rgba(0, 0, 0, 0.8);
            color: white;
            padding: 10px;
            border-radius: 4px;
            font-size: 14px;
            display: none;
            pointer-events: none;
            z-index: 100;
        }}
        .tooltip strong {{
            display: block;
            margin-bottom: 4px;
        }}
    </style>
</head>
<body>
    <header>
        <nav>
            <a href="index.html">Home</a>
            <a href="runs.html">Runs</a>
            <a href="knowledge_base.html">Knowledge Base</a>
            <a href="tools.html">Tools</a>
        </nav>
    </header>
    <main>
        <h1>Run History</h1>
        <p>Total: {len(runs)} runs</p>
        <div class="timeline-container">
            <svg width="{svg_width}" height="{svg_height}" class="timeline">
                {"".join(timeline_lines)}
                {"".join(marks)}
            </svg>
        </div>
        <div id="tooltip" class="tooltip"></div>
    </main>
    <footer>
        <p>Generated by drift build script</p>
    </footer>
    <script>
        const tooltip = document.getElementById('tooltip');
        const marks = document.querySelectorAll('circle[data-run]');
        
        marks.forEach(mark => {{
            mark.addEventListener('mouseenter', (e) => {{
                const run = e.target.dataset.run;
                const date = e.target.dataset.date;
                const ended = e.target.dataset.ended;
                tooltip.innerHTML = '<strong>Run {run}</strong>{date} - {ended}';
                tooltip.style.display = 'block';
            }});
            
            mark.addEventListener('mousemove', (e) => {{
                tooltip.style.left = e.pageX + 10 + 'px';
                tooltip.style.top = e.pageY - 10 + 'px';
            }});
            
            mark.addEventListener('mouseleave', () => {{
                tooltip.style.display = 'none';
            }});
        }});
    </script>
</body>
</html>"""
    
    with open(DOCS_DIR / "runs.html", "w") as f:
        f.write(html)
    print("Generated runs.html")

# Generate index page
def generate_index():
    """Generate index.html homepage."""
    # Get latest post
    latest = sorted(POSTS)[-1]
    
    with open(latest) as f:
        body = f.read()
    
    from markdown import markdown
    html_body = markdown(body, extensions=["fenced_code", "tables"])
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drift - Your Agent's History</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <nav>
            <a href="index.html">Home</a>
            <a href="runs.html">Runs</a>
            <a href="knowledge_base.html">Knowledge Base</a>
            <a href="tools.html">Tools</a>
        </nav>
    </header>
    <main>
        <h1>Drift</h1>
        <p>Your agent's history, live and on the web.</p>
        <div class="posts">
            <h2>Latest Post</h2>
            <div class="post-preview">
                <h3>{latest.stem}</h3>
                {html_body[:500]}...
            </div>
        </div>
        <div class="links">
            <a href="runs.html" class="btn">View All Runs</a>
            <a href="knowledge_base.html" class="btn">Knowledge Base</a>
            <a href="tools.html" class="btn">Tools</a>
        </div>
    </main>
    <footer>
        <p>Generated by drift build script</p>
    </footer>
</body>
</html>"""
    
    with open(DOCS_DIR / "index.html", "w") as f:
        f.write(html)
    print("Generated index.html")

# Main build function
def main():
    """Run the full build process."""
    print("Starting build...")
    
    # Generate all pages
    generate_index()
    generate_posts()
    generate_runs_json()
    runs = generate_runs_json()
    generate_runs_page(runs)
    generate_knowledge_base()
    generate_tools()
    
    print("\nBuild complete!")

if __name__ == "__main__":
    main()
